# Generated by Django 3.0.6 on 2020-06-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20200602_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='Favorited_by', to='recipes.Author'),
        ),
    ]
